In [48]:

import pandas as pd

airbnb = pd.read_csv("listings dec21.csv")


list(airbnb.columns)

new_airbnb = airbnb[["name", "latitude", "longitude", "bedrooms", "price"]]

In [49]:
new_airbnb

,name,latitude,longitude,bedrooms,price
0,Belém 1 Bedroom Historical Apartment,38.697500,-9.197680,1.0,$40.00
1,Heart of Alfama Lisbon Center - Cœur de l'Alfama,38.712410,-9.127060,1.0,$50.00
2,Apartamento Alfama com vista para o rio!,38.710820,-9.127190,1.0,$60.00
3,Alfama Hill - Boutique apartment,38.711560,-9.129870,1.0,$60.00
4,TheHOUSE - Your luxury home,38.711080,-9.159790,9.0,$957.00
...,...,...,...,...,...
18521,Zen Nest in the heart of Lisbon,38.721587,-9.143302,1.0,$40.00
18522,NEW! Charming 2 bed w/patio in historical Mour...,38.716469,-9.132524,2.0,$75.00
18523,New Avenues Dreamy Home,38.740442,-9.149162,2.0,$150.00
18524,Alfama Top Location 2,38.715410,-9.132390,1.0,$55.00
18525,Stunning Apartment in Heart of Lisbon by Lovel...,38.709519,-9.136877,2.0,$114.00